# this files gets expanded by Gradle to contain the values at build time so you need to escape anything you don't want expanded

endpoints:
    health:
        sensitive: false

info:
    app:
        name: ${name}
        description: ${description}
        version: ${version}

logging:
    config: classpath:logback.xml

management:
    contextPath: /operations
    security:
        enabled: false
        role: admin
        sessions: stateless

security:
    user:
        name: developer
        password: developer
    basic:
        enabled: false
        realm: example

server:
    port: 2020
    contextPath: /

spring:
    application:
        name: ${name}
    cloud:
        bus:
            enabled: false
        config:
            server:
                git:
                    uri: https://github.com/kurron/spring-configuration-files.git
        consul:
            host: localhost
            port: 8500
            discovery:
                healthCheckInterval: 15s
                healthCheckPath: /operations/health
                instanceId: \${spring.application.name}:\${random.int[1024,65536]}
                preferAgentAddress: true
                preferIpAddress: true
    main:
        banner-mode: console
    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true
        serialization-inclusion: non_empty
