endpoints:
    health:
        sensitive: false

logging:
    config: classpath:logback.xml

management:
    contextPath: /operations
    security:
        enabled: false
        role: admin
        sessions: stateless

security:
    user:
        name: developer
        password: developer
    basic:
        enabled: false
        realm: example
server:
    port: 2020
    contextPath: /

spring:
    application:
        name: ${SERVICE_NAME:configuration-server}
    cloud:
        bus:
            enabled: false
        config:
            server:
                git:
                    uri: ${GIT_URI:https://github.com/kurron/spring-configuration-files.git}
        consul:
            host: ${CONSUL_HOST:localhost}
            port: ${CONSUL_PORT:8500}
            discovery:
                healthCheckInterval: 15s
                healthCheckPath: /operations/health
                instanceId: ${SERVICE_NAME:configuration-server}:${random.int[1024,65536]}
                preferAgentAddress: true
                preferIpAddress: true
    main:
        banner-mode: console
    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true
        serialization-inclusion: non_empty
