# this file gets expanded by Gradle to contain the values at build time so you need to escape anything you don't want expanded
info:
    app:
        name: ${name}
        description: ${description}
        version: ${version}
        built-on: ${builtOn}

logging:
    config: classpath:logback.xml

management:
    contextPath: /operations
    security:
        enabled: false
        role: admin
        sessions: stateless

endpoints:
    health:
        time-to-live: 1000
        sensitive: false

security:
    user:
        name: operations
        password: operations
    basic:
        enabled: false
        realm: configuration

server:
    contextPath: /
    port: 8080
    useForwardHeaders: true
    tomcat:
        portHeader: X-Forwarded-Port
        protocolHeader: X-Forwarded-Protocol-Header
        remoteIpHeader: X-Forwarded-Remote-IP-Header

spring:
    application:
        name: ${name}
    cloud:
        bus:
            enabled: false
        config:
            server:
                git:
                    uri: https://github.com/kurron/spring-configuration-files.git
                health:
                    # there is a bug/feature where the hitting the health endpoint causes the server to refresh with Git
                    # https://github.com/spring-cloud/spring-cloud-config/issues/423
                    enabled: false
        consul:
            host: consul
            port: 8500
            discovery:
                aclToken:
                catalogServicesWatchDelay: 10
                catalogServicesWatchTimeout: 2
                enabled: true
                healthCheckInterval: 15s
                healthCheckPath: \${management.contextPath}/health
                healthCheckTimeout: 5s
                healthCheckUrl:
                heartbeat:
                    enabled: false
                    ttlValue: 30
                hostname:
                ipAddress:
                instanceId: \${spring.application.name}:\${random.int[1024,65536]}
                lifecycle:
                    enabled: true
                managementSuffix: management
                managementTags:
                    - management
                port: \${server.port}
                preferAgentAddress: true
                preferIpAddress: true
                register: true
                registerHealthCheck: true
                scheme: http
                queryPassing: false
                serviceName: \${spring.application.name}
                serverListQueryTags:
                    some-key: some-value
                tags:
                    - ${version}
    main:
        banner-mode: console
    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true
        sdefault-property-inclusion: non_empty
