endpoints:
    health:
        sensitive: false
logging:
    config: classpath:logback.xml
info:
    app:
        name: ${name}
        description: ${description}
        version: ${version}
management:
    contextPath: /operations
    security:
        enabled: false
        role: admin
        sessions: stateless

security:
    user:
        name: developer
        password: developer
    basic:
        enabled: false
        realm: example
server:
    port: 2020
    contextPath: /

spring:
    application:
        name: CONFIGSERVER
    cloud:
        config:
#            discovery:
#                enabled: true
            server:
                git:
                    uri: https://github.com/kurron/spring-configuration-files.git
        consul:
            host: localhost
            port: 8500
            discovery:
                healthCheckInterval: 15s
                healthCheckPath: /operations/health
                instanceId: CONFIGSERVER:1
                preferAgentAddress: true
                preferIpAddress: true
    main:
        banner-mode: console
    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true
        serialization-inclusion: non_empty
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        virtualHost: /
        username: guest
