spring:
  cloud:
      config:
          server:
              git:
                  uri: https://raw.githubusercontent.com/kurron/spring-configuration-server/master/configuration
  main:
    banner-mode: console
  groovy:
    template:
      check-template-location: false
  jackson:
    serialization:
      indent_output: true
    serialization-inclusion: non_empty

management:
    context-path: /operations

endpoints:
  health:
    sensitive: false

server:
  port: 2020
  contextPath: /

logging:
  config: classpath:logback.xml

info:
  app:
    name: ${name}
    description: ${description}
    version: ${version}

security:
  user:
    name: developer
    password: developer
  basic:
    enabled: false
    realm: example